<!DOCTYPE html>

<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%> 

    <html xmlns="http://www.w3.org/1999/xhtml"  ><head>
	<title>GitHub Resume</title>
	
	<meta http-equiv="content-type" content="text/html; charset=utf-8">
	<meta name="keywords" content="cv, resume, hResume, github, community, free, fun, nice, useful">
	<meta name="description" content="GitHub resumes, generated by the community, for the community.">
	<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.7.0/build/reset-fonts-grids/reset-fonts-grids.css" media="all"> 
	<link rel="stylesheet" type="text/css" href="http://resume.github.io/css/resume.css" media="all">
	<link rel="stylesheet" type="text/css" href="http://resume.github.io/css/print.css" media="print">
	<script type="text/javascript" async="" src="http://www.google-analytics.com/ga.js"></script><script type="text/javascript" src="http://code.jquery.com/jquery-1.8.1.min.js"></script>
	<script type="text/javascript" src="http://resume.github.io/js/mustache.js"></script>
	<script type="text/javascript" src="http://resume.github.io/js/githubresume.js"></script>
	<script src="${pageContext.request.contextPath}/resources/js/gitcv.js"></script>
</head>
<body id="resume"><div id="doc" class="yui-t7">
   <div id="hd" role="banner"><h1>My GITHUB Resume</h1></div>
   <div id="bd" role="main">
    <div class="yui-g">
        <p class="enlarge-medium">
            As a software startup owner I really enjoy when people send us their
            resumes and they include their github account so we can see tangible work they have done. 
        </p>
        <p><br></p>
        <p class="enlarge-medium">
            After a <a href="https://twitter.com/#!/jeresig/status/33968704983138304">tweet by John Resig</a>
            I imagined that it may be nice for people to be able to generate their <a href="https://github.com" title="GitHub">GitHub</a> résumés.
        </p>
        <p><br><br></p>

        <form id="run" action="." method="get">
            <p>
                <input id="username" type="text" placeholder="Enter your github username and click on generate">
                <button   id="gen">Generate</button>
            </p>
        </form>

    </div>
    
     <div class="yui-a">
      
  
       
    </div>
    
    <div id="examples" class="yui-g">
        <p><br><br></p>
        <h2>See some popular users</h2>
        <div class="yui-gb">
            <ul>
                <li><a href="/?mxcl" title="Max Howell">Max Howell</a></li>
                <li><a href="/?mojombo" title="Tom Preston-Werner">Tom Preston-Werner</a></li>

                <li><a href="/?madrobby" title="Thomas Fuchs">Thomas Fuchs</a></li>
                <li><a href="/?paulirish" title="Paul Irish">Paul Irish</a></li>
                <li class=""><a href="/?michaeldv" title="Michael Dvorkin">Michael Dvorkin</a></li>
            </ul>
        </div>
        <div class="yui-gb">
            <ul>
                <li><a href="/?mislav" title="Mislav Marohnić">Mislav Marohnić</a></li>
                <li><a href="/?justinfrench" title="Justin French">Justin French</a></li>
                <li><a href="/?ry" title="Ryan Dahl">Ryan Dahl</a></li>
                <li><a href="/?joshuaclayton" title="Joshua Clayton">Joshua Clayton</a></li>
                <li class=""><a href="/?defunkt" title="Chris Wanstrath">Chris Wanstrath</a></li>
            </ul>
        </div>
        <br>
    </div>

    <div class="yui-g last">
        <div class="yui-main">
            <br><br>
            <h2>Notes, Information and Future features</h2>
            <p class="enlarge-medium"><br>
            This is the first version. I am planning on adding
            things as such as your most committed forks, most committed repositories and make the "My Popular Repositories" be built from
            your complete list of repositories. Feel free to <a href="https://github.com/resume/resume.github.com">fork the page</a> if you want to help :-)
            <br><br>
            </p>
        </div>

    </div>

   <div id="ft" role="contentinfo"><p>Brought to you by the brilliant mind of <a href="http://twitter.com/davidcoallier">@davidcoallier</a> &lt;/modesty&gt; — Résumé Template from <a href="http://thingsthatarebrown.com/blog/2009/05/sample-resume-template/">Things That Are Brown</a></p></div>
</div>


</div></body></html>